# Generated by Django 4.0.4 on 2022-04-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_inflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='registered_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='registered_by',
            field=models.CharField(default=0, max_length=55),
        ),
    ]
