# Generated by Django 4.0.1 on 2022-05-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_outflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='billet_code',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='payment_code',
        ),
    ]
